<template>
    <div class="text-white">
        <div>Hi, my name is</div>
        <div>Kristian Michel</div>
        <div>I am currently a student at the University of Central Florida studying Computer Science. My interests currently reside in video game and web development. 
            However, I am passionate about providing innovative solutions to complex problems, so I am open to any opportunity to grow my skills in programming.
        </div>
    </div>
</template>